service: stock-notifier
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-south-1
  environment:
    ONESIGNAL_APP_ID: "b7810c20-2c37-4c13-bfd8-4ae59d3252ae"
    ONESIGNAL_AUTH_KEY: "Basic Y2U2MTQxZjYtMTY3My00MzhiLWE5YjQtMjFlM2VmYTkzZmQy"
functions:
  stocknotifier:
    handler: handler.stocknotifier